'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const context = {window:{}};
vm.runInNewContext(fs.readFileSync('utils/video_similarity/assets/compare-metrics.js','utf8'),context);
const compare = context.window.CompareMetrics.compare;
const a={duration:'0:12',durationSeconds:12.1,resolution:'1920x1080',size:'6.0MB',sizeBytes:6000000};
const b={duration:'0:12',durationSeconds:12.8,resolution:'1080x1920',size:'2.0MB',sizeBytes:2000000};
let rows=compare(a,b);
assert.equal(rows[0].winner,'B');
assert.match(rows[0].note,/0.7 秒/);
assert.equal(rows[1].winner,null);
assert.match(rows[1].note,/尺寸不同/);
assert.equal(rows[2].winner,'A');
assert.match(rows[2].note,/200.0%/);
assert.ok(compare(a,a).every(row=>row.winner===null&&row.note==='两者相同'));
assert.ok(compare({},{}).every(row=>row.winner===null&&row.note==='参数不可用'));
assert.equal(compare({size:'950KB'},{size:'1MB'})[2].winner,'B');
console.log('Comparison metrics: precise duration, orientation, units, equality and missing values passed.');

assert.equal(compare({durationSeconds:59.999},{durationSeconds:60})[0].left,'1:00');
assert.equal(compare({durationSeconds:0},{durationSeconds:0})[0].left,'0:00');
